[project]
name = "static-site-generator"
version = "0.1.0"
description = "A static site generator built with Python. Refering to boot dev tutorial."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
